### ISSUE TITLE
Warning `already initialized constant MRZ::TD3Parser::FORMAT_ONE`

### ISSUE THREAD

**Issue by jjf21** [mindee/mindee-api-ruby#18]
Hi there,

I juste add mindee gem to my Rails app, and I got those warnings when launching a console

```
/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/mindee-2.1.0/lib/mindee/parsing/prediction/passport/passport_v1.rb:15: warning: already initialized constant MRZ::TD3Parser::FORMAT_ONE
/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/mrz-0.2.0/lib/mrz/td3_parser.rb:3: warning: previous definition of FORMAT_ONE was here
```

Any idea on how to solve this ?
Thanks

**Comment by jjf21** [comment]
Ok just saw [this PR](https://github.com/streetspotr/mrz/pull/3), could you keep me updated ?

**Comment by ianardee** [comment]
Yup, still waiting for the PR to merged... it's been several months already so not holding my breath.

We'll probably just move the MRZ validation to the server side and get rid of this dependency.

I'll close this ticket when done.
